language: c
compiler:
    - gcc
    - clang
script:
    - make
branches:
    only:
        - master
notifications:
    recipients:
        - gang.zhuo@gmail.com
    email:
        on_success: change
        on_failure: always
