#!/bin/sh /etc/rc.common
# cleandns init script

START=90

USE_PROCD=1

start_cleandns() {
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param nice -5
	procd_set_param limits nofile="65535 65535"
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_append_param limits core="unlimited"
	}
	procd_set_param command /usr/bin/cleandns
	procd_append_param command --config /etc/config/cleandns
	procd_close_instance
}

start_service() {
	start_cleandns
}
